### ISSUE TITLE
Errors after updating the bot

### ISSUE THREAD

**Issue by namjeff** [40Cakes/pokebot-gen3#448]
I just updated the bot and when it tries to update my files after starting my profile, it freezes and then immediately starts generating extremely lengthy error log that goes beyond the scroll limit and ends up with "AttributeError: 'NoneType' object has no attribute 'pokemon'"
Once this is done, I can start the game, but all progress shown ( number of encounters ..etc. ) starts again from 0
I can't figure out how to copy the entire log, so let me know if there is something I can do.

**Comment by PeteKempDojo** [comment]
We have this fixed in the main branch and it's awaiting a few other things before a release.

Until then please replace `modules/stats_migrate.py` with this file:
https://raw.githubusercontent.com/hanzi/pokebot-gen3/f6a154892c8dcc4864fbdf48159dfee69e8f59b7/modules/stats_migrate.py

You will need to delete `profiles/{name}/stats.db` from your profile folder to force the migration to start again, but this should fix it :)

**Comment by namjeff** [comment]
Thank you, that worked!
