### ISSUE TITLE
Jap FR Static soft resets not working

### ISSUE THREAD

**Issue by Rain46092** [40Cakes/pokebot-gen3#490]
**Description:**

Using static soft reset on a Japanese Fire Red copy has no inputs pressed.

**Media:**

![hash verification](https://github.com/user-attachments/assets/466a333d-0cd1-42d3-a69d-caff9e45e06f)
Hash verification of the ROM I am using (dumped from official cartridge)

[https://youtu.be/Ei690Pg4QFw](url)
Video of what occurs when the mode selected (bot delivers no inputs)

**Comment by ThibaultLassiaz** [comment]
Hello!

It’s normal that the mode isn’t working because you’re using the latest release of the bot, which came out on October 23rd. I just added support for this mode in Fire Red Japanese yesterday, so it's currently only available in the development version. This might be a bit confusing, but if you want to check which modes your bot supports, it’s better to look at the `wiki` folder in your own installation, rather than in the repository’s `wiki` folder.

If you’d like to use this mode anyway, consider using the [development version](https://github.com/40Cakes/pokebot-gen3/archive/refs/heads/main.zip) of the bot, though keep in mind as it is a dev version, it might be unstable at times.

Let me know if you're having issues with it!

**Comment by Rain46092** [comment]
ah sorry my mistake i saw the pull request on the discord and then went to try it out, it didnt even cross my mind it had to be approved

**Comment by ThibaultLassiaz** [comment]
> ah sorry my mistake i saw the pull request on the discord and then went to try it out, it didnt even cross my mind it had to be approved

It's approved and merged, so available on the dev version. Either switch to dev version or wait for the next release 😄
