### ISSUE TITLE
Dump shinies/party/PC to .pk3 files

### ISSUE THREAD

**Issue by 40Cakes** [40Cakes/pokebot-gen3#76]
# Dump shinies/party/PC to .pk3 files

Add an option to dump shiny encounters or custom catch filtered Pokémon to raw byte .pk3 files to be imported into PKHeX or shared in [#pkhexchange💱](https://discord.com/channels/1057088810950860850/1123523909745135616).

Some users have requested being able to save state on each shiny and just continue running the bot while auto-catch is still in the works, I think this feature is probably a lot better to use while utilising the catch block list + allows for dumping/backing up party and PC Pokémon.

PKHeX .pk3 naming convention:
`<dex_num> <shiny ★> - <mon_name> - <pid>.pk3` (`0273 ★ - SEEDOT - C88CF14B19C6.pk3`)

### Required
- [x] Dump shiny encounters
- [x] Dump custom catch filtered Pokémon
- [x] Follow the same naming convention as PKHeX

## Notes
This issue has been raised to track the work/progress for this new feature/functionality.

Please keep your PR in draft until it is ready to be reviewed and tested. Referencing this issue in your PR description will allow for collaboration among many, and also just lets us know you're working on it, potentially saving someone else from wasting their time working on the same thing separately.

Don't be afraid to use this issue or visit the Discord channel [#development-chat🛠](https://discord.com/channels/1057088810950860850/1111076425559199787) to ask for help or discuss ideas related to this issue.

**Comment by pekempy** [comment]
The option to include IV sum and possibly nature in file name would be nice too, to be able to easily visually compare mons.

E.g.
`0273 ★ - SEEDOT - Modest [180] - C88CF14B19C6.pk3`

**Comment by pekempy** [comment]
#80 should be ready for review now - backup of PC is included as part of PKHeX so unnecessary to add this to the bot

**Comment by randomdice101** [comment]
I know this issue is closed and its been a while, however the exported files are encrypted, non decrypted. Could you set the extension to ek3? This is what is used for encrypted files as seen here https://github.com/kwsch/PKHeX/blob/06b8ec03ae6c365fe9ca3ea02b7d74b4bf3fab36/PKHeX.Core/Util/FileUtil.cs#L307 

Pkhex can work with either format, however other programs don't always detect if something is or isn't encrypted.

Example:
EK3 (raw dump from the bot)
![image](https://github.com/40Cakes/pokebot-gen3/assets/4016932/b1d776f5-9003-4762-9c16-f0751b6fe9ef)
PK3 dumped by pkhex after saving.
![image](https://github.com/40Cakes/pokebot-gen3/assets/4016932/b2c9edf2-7aab-4804-936a-4ddd807824da)
0x20-0x4F are not decrypted.
